from django.db import models

# Create your models here.
class SecondHandCarAIModel(models.Model):
    box_1 = models.CharField(max_length=999, verbose_name='駆動方式')
    box_2 = models.CharField(max_length=999, verbose_name='乗車定員')
    box_3 = models.CharField(max_length=999, verbose_name='ドア枚数')
    box_4 = models.CharField(max_length=999, verbose_name='エンジン型式')
    box_5 = models.CharField(max_length=999, verbose_name='エンジン種類')
    box_6 = models.CharField(max_length=999, verbose_name='エンジン区分')
    box_7 = models.CharField(max_length=999, verbose_name='環境対策エンジン')
    box_8 = models.CharField(max_length=999, verbose_name='総排気量(cc)')
    box_9 = models.CharField(max_length=999, verbose_name='過給器')
    box_10 = models.CharField(max_length=999, verbose_name='ホイールベース(mm)')
    box_11 = models.CharField(max_length=999, verbose_name='車両重量(kg)')
    box_12 = models.CharField(max_length=999, verbose_name='最低地上高(mm)')
    box_13 = models.CharField(max_length=999, verbose_name='最小回転半径(m)')
    box_14 = models.CharField(max_length=999, verbose_name='サスペンション形式前')
    box_15 = models.CharField(max_length=999, verbose_name='サスペンション形式後')
    box_16 = models.CharField(max_length=999, verbose_name='ブレーキ形式後')
    box_17 = models.CharField(max_length=999, verbose_name='使用燃料')
    box_18 = models.CharField(max_length=999, verbose_name='燃料タンク容量(L)')
    box_19 = models.CharField(max_length=999, verbose_name='エアフィルター')
    box_20 = models.CharField(max_length=999, verbose_name='2列目シート')
    box_21 = models.CharField(max_length=999, verbose_name='アルミホイール')
    box_22 = models.CharField(max_length=999, verbose_name='リアスポイラー')
    box_23 = models.CharField(max_length=999, verbose_name='フロントフォグランプ')
    box_24 = models.CharField(max_length=999, verbose_name='ETC')
    box_25 = models.CharField(max_length=999, verbose_name='助手席エアバッグ')
    box_26 = models.CharField(max_length=999, verbose_name='サイドエアバッグ')
    box_27 = models.CharField(max_length=999, verbose_name='カーテンエアバッグ')
    box_28 = models.CharField(max_length=999, verbose_name='頸部衝撃緩和ヘッドレスト')
    box_29 = models.CharField(max_length=999, verbose_name='EBD付ABS')
    box_30 = models.CharField(max_length=999, verbose_name='セキュリティアラーム')
    box_31 = models.CharField(max_length=999, verbose_name='マニュアルモード')
    box_32 = models.CharField(max_length=999, verbose_name='チップアップシート')
    box_33 = models.CharField(max_length=999, verbose_name='ドアイージークローザー')
    box_34 = models.CharField(max_length=999, verbose_name='レーンアシスト')
    box_35 = models.CharField(max_length=999, verbose_name='車間距離自動制御システム')
    box_36 = models.CharField(max_length=999, verbose_name='前席シートヒーター')
    box_37 = models.CharField(max_length=999, verbose_name='床下ラゲージボックス')
    box_38 = models.CharField(max_length=999, verbose_name='オーディオソース_DVD')
    box_39 = models.CharField(max_length=999, verbose_name='ブレーキアシスト')
    box_40 = models.CharField(max_length=999, verbose_name='駐車支援システム')
    box_41 = models.CharField(max_length=999, verbose_name='防水加工')
    box_42 = models.CharField(max_length=999, verbose_name='地上波デジタルテレビチューナー')
    box_43 = models.CharField(max_length=999, verbose_name='ソナー')
    box_44 = models.CharField(max_length=999, verbose_name='サイドモニター')
    box_45 = models.CharField(max_length=999, verbose_name='その他ナビゲーション')
    box_46 = models.CharField(max_length=999, verbose_name='インテリジェントAFS')
    box_47 = models.CharField(max_length=999, verbose_name='運転席パワーシート')
    box_48 = models.CharField(max_length=999, verbose_name='本革シート')
    box_49 = models.CharField(max_length=999, verbose_name='AC電源')
    box_50 = models.CharField(max_length=999, verbose_name='ステアリングヒーター')
    box_51 = models.CharField(max_length=999, verbose_name='リアフォグランプ')
    box_52 = models.CharField(max_length=999, verbose_name='レインセンサー')
    box_53 = models.CharField(max_length=999, verbose_name='インテリジェントパーキングアシスト')
    box_54 = models.CharField(max_length=999, verbose_name='エマージェンシーサービス')
    box_55 = models.CharField(max_length=999, verbose_name='フロント両席パワーシート')
    box_56 = models.CharField(max_length=999, verbose_name='オーディオソース_HDD')
    box_57 = models.CharField(max_length=999, verbose_name='ニーエアバッグ')
    box_58 = models.CharField(max_length=999, verbose_name='ヘッドライトウォッシャー')
    box_59 = models.CharField(max_length=999, verbose_name='後退時連動式ドアミラー')
    box_60 = models.CharField(max_length=999, verbose_name='VGS/VGRS')
    box_61 = models.CharField(max_length=999, verbose_name='ABS')
    box_62 = models.CharField(max_length=999, verbose_name='2列目ウォークスルー')
    box_63 = models.CharField(max_length=999, verbose_name='3列目シート')
    box_64 = models.CharField(max_length=999, verbose_name='電動バックドア')
    box_65 = models.CharField(max_length=999, verbose_name='リアエンターテイメントシステム')
    box_66 = models.CharField(max_length=999, verbose_name='電気式4WD')
    box_67 = models.CharField(max_length=999, verbose_name='HDDナビゲーション')
    box_68 = models.CharField(max_length=999, verbose_name='全長(mm)')
    box_69 = models.CharField(max_length=999, verbose_name='全幅(mm)')
    box_70 = models.CharField(max_length=999, verbose_name='全高(mm)')
    box_71 = models.CharField(max_length=999, verbose_name='室内全長(mm)')
    box_72 = models.CharField(max_length=999, verbose_name='室内全幅(mm)')
    box_73 = models.CharField(max_length=999, verbose_name='室内全高(mm)')
    box_74 = models.CharField(max_length=999, verbose_name='マニュアルエアコン')
    box_75 = models.CharField(max_length=999, verbose_name='片側スライドドア')
    box_76 = models.CharField(max_length=999, verbose_name='最高出力(ps)')

    def __str__(self):
         return '<secondhandcar_id=' + str(self.id) + '>'


class SecondHandCarInfoModel(models.Model):
    second_hand_car_id = models.ForeignKey(SecondHandCarAIModel, verbose_name='中古車ID', on_delete=models.PROTECT)
    parent_category = models.CharField(max_length=999, verbose_name='メーカー')
    category = models.CharField(max_length=999, verbose_name='車種')
    grade = models.CharField(max_length=999, verbose_name='グレード')
    release_period = models.CharField(max_length=999, verbose_name='発売期間')
    model = models.CharField(max_length=999, verbose_name='型式')
    img1 = models.URLField(verbose_name='img1')
    img2 = models.URLField(verbose_name='img2')
    img3 = models.URLField(verbose_name='img3')

    def __str__(self):
         return str(self.second_hand_car_id)


class SecondHandCarPriceModel(models.Model):
    second_hand_car_id = models.ForeignKey(SecondHandCarAIModel, verbose_name='中古車ID', on_delete=models.PROTECT)
    day = models.CharField(max_length=10)
    price = models.CharField(max_length=999, blank=True, null=True)

    def __str__(self):
         return str(self.second_hand_car_id)